@hostname = http://localhost:1982
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJzYXRyeWFAZnJlc2hjbXMubmV0IiwiZnVsbF9uYW1lIjoiU2F0cnlhIFdpZ3VuYSIsIm5pY2tfbmFtZSI6IlNhdHJ5YSIsImlhdCI6MTY0NTQ1MzE3OCwiZXhwIjoxNjQ1NDU2Nzc4fQ.7U3Z1XtB0kxUc_3z9qC3bwQ5dtwFqmDOyjahYcYkrY4

POST {{hostname}}/register HTTP/1.1
content-type: application/json

{
    "email": "arshakaela@freshcms.com",
    "password": "123456789",
    "password_confirmation": "123456789",
    "full_name": "Arsha Kaela",
    "nick_name": "Kaela"
}

###

POST {{hostname}}/login HTTP/1.1
content-type: application/json

{
    "email": "satrya@freshcms.net",
    "password": "123456789"
}

###

GET {{hostname}}/auth HTTP/1.1
content-type: application/json
authorization: {{token}}

###

GET {{hostname}}/users HTTP/1.1
content-type: application/json
authorization: {{token}}

###

GET {{hostname}}/user/1 HTTP/1.1
content-type: application/json
authorization: {{token}}