@hostname = http://localhost:8669
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJzYXRyeWFAZnJlc2hjbXMubmV0IiwiZnVsbF9uYW1lIjoiU2F0cnlhIFdpZ3VuYSIsIm5pY2tfbmFtZSI6IlNhdHJ5YSIsImlhdCI6MTY0NTg1NDY2OSwiZXhwIjoxNjQ1OTQxMDY5fQ.5av8ht_6OKm2xtaFVVUj9SQowrxhjFP3mFTKyv9vXd0

POST {{hostname}}/register HTTP/1.1
content-type: application/json

{
    "email": "arshakaela@freshcms.com",
    "password": "123456789",
    "password_confirmation": "123456789",
    "full_name": "Arsha Kaela",
    "nick_name": "Kaela"
}

###

POST {{hostname}}/login HTTP/1.1
content-type: application/json

{
    "email": "satrya@freshcms.net",
    "password": "123456789"
}

###

DELETE {{hostname}}/logout HTTP/1.1
content-type: application/json

###

GET {{hostname}}/refresh-token HTTP/1.1
content-type: application/json

###

GET {{hostname}}/auth HTTP/1.1
content-type: application/json
authorization: {{token}}

###

GET {{hostname}}/users HTTP/1.1
content-type: application/json
authorization: {{token}}

###

GET {{hostname}}/user/1 HTTP/1.1
content-type: application/json
authorization: {{token}}

###

POST {{hostname}}/user HTTP/1.1
content-type: application/json
authorization: {{token}}

{
    "email": "ambarawa@freshcms.net",
    "password": "123456789",
    "password_confirmation": "123456789",
    "full_name": "Ambarawa Kesawa",
    "nick_name": "Ambarawa",
    "gender": "male",
    "address": "No address",
    "phone": "888-888-888"
}

###

PUT {{hostname}}/user/4 HTTP/1.1
content-type: application/json
authorization: {{token}}

{
    "full_name": "Riana Laskmi Dewi",
    "nick_name": "Riana",
    "gender": "female",
    "address": "Br. Pasedana, Gg Mawar No 2, Gianayr - Bali",
    "phone": "888-777-666"
}

###

DELETE {{hostname}}/user/6 HTTP/1.1
content-type: application/json
authorization: {{token}}

###

GET {{hostname}}/profile/me HTTP/1.1
content-type: application/json
authorization: {{token}}

###

PUT {{hostname}}/profile/me HTTP/1.1
content-type: application/json
authorization: {{token}}

{
    "full_name": "Satrya Wiguna",
    "nick_name": "Satrya",
    "gender": "male",
    "address": "No address",
    "phone": "999-999-999"
}